package VISTAS;


import com.sun.net.httpserver.Authenticator;
import java.awt.Desktop;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import rojerusan.RSAnimation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Elber
 */
public class frm_AcercaD extends javax.swing.JFrame {
 private ImageIcon imageicono;
    /**
     * Creates new form frmas
     */
    public frm_AcercaD() {
//        imageicono = new ImageIcon(this.getClass().getResource("/appapagar/image/stopwatch.png"));
        imageicono = new ImageIcon(this.getClass().getResource("/appapagar/image/logo1.png"));
        initComponents();
         RSAnimation.setBajar(-500, 140, 2, 2, this);
        //centrar el formulario
        setLocationRelativeTo(null);
        //logo
         this.setIconImage(imageicono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnregistrarse = new rojerusan.RSMaterialButtonRound();
        btnregistrarse1 = new rojerusan.RSMaterialButtonRound();
        lcliente12 = new javax.swing.JLabel();
        btnsalir = new rojerusan.RSButtonTriangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnregistrarse2 = new rojerusan.RSMaterialButtonRound();
        btnregistrarse6 = new rojerusan.RSMaterialButtonRound();
        btnregistrarse7 = new rojerusan.RSMaterialButtonRound();
        pnlEncabezado = new javax.swing.JPanel();
        btnVentanaD = new rojeru_san.RSButton();
        lblmin = new javax.swing.JLabel();
        lcliente11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblvadera = new javax.swing.JLabel();
        btncerrarS = new rojerusan.RSMaterialButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 179, 135)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnregistrarse.setBackground(new java.awt.Color(66, 148, 255));
        btnregistrarse.setText("F");
        btnregistrarse.setToolTipText("");
        btnregistrarse.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 40, 40));

        btnregistrarse1.setBackground(new java.awt.Color(223, 0, 34));
        btnregistrarse1.setText("p");
        btnregistrarse1.setToolTipText("");
        btnregistrarse1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnregistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarse1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 40, 40));

        lcliente12.setBackground(new java.awt.Color(255, 255, 255));
        lcliente12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lcliente12.setForeground(new java.awt.Color(0, 153, 255));
        lcliente12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcliente12.setText("INFORMACIÓN");
        jPanel4.add(lcliente12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 20));

        btnsalir.setBackground(new java.awt.Color(255, 204, 0));
        btnsalir.setMnemonic('x');
        btnsalir.setToolTipText("cerrar");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 349, 30, 30));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Montserrat", 2, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Cusco code \nAgencia de desarrollo de sofware, desarrollo web y Marketing.\n\nVersión del producto: Software de Ticket 1.0\nActualizaciones disponibles a la versión  1.5\n\nPagina Web...\nwww.cuscocode.com\n\nContactos\n+51 997 801 982 : Elvert C. M. Surco\n+51 940 500 006 : Ing. Raul Gabriel H. C");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(204, 255, 255));
        jTextArea1.setPreferredSize(new java.awt.Dimension(1900, 136));
        jTextArea1.setSelectionColor(new java.awt.Color(0, 153, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 310, 270));

        btnregistrarse2.setBackground(new java.awt.Color(70, 187, 151));
        btnregistrarse2.setText("w");
        btnregistrarse2.setToolTipText("");
        btnregistrarse2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnregistrarse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarse2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrarse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 40, 40));

        btnregistrarse6.setBackground(new java.awt.Color(26, 145, 218));
        btnregistrarse6.setText("t");
        btnregistrarse6.setToolTipText("");
        btnregistrarse6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnregistrarse6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarse6ActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrarse6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 40, 40));

        btnregistrarse7.setBackground(new java.awt.Color(255, 0, 0));
        btnregistrarse7.setText("Y");
        btnregistrarse7.setToolTipText("");
        btnregistrarse7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnregistrarse7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarse7ActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrarse7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 40, 40));

        pnlEncabezado.setBackground(new java.awt.Color(0, 153, 153));
        pnlEncabezado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlEncabezadoMouseDragged(evt);
            }
        });
        pnlEncabezado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlEncabezadoMousePressed(evt);
            }
        });
        pnlEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentanaD.setBackground(new java.awt.Color(255, 51, 102));
        btnVentanaD.setForeground(new java.awt.Color(0, 153, 0));
        btnVentanaD.setText("x");
        btnVentanaD.setToolTipText("<html> \n<style>\n        div{\n            background-color: #284564 ;\n            color: white;\n            font-family: fantasy;\n            display: flex;\n            align-items: center;\n            justify-content: center;       \n        }\n        h3{\n           margin: 4px;\n        }\n    </style>\n<div>\n        <h3>\n            Mas opciones\n        </h3> \n</div>\n</html>");
        btnVentanaD.setColorHover(new java.awt.Color(0, 0, 51));
        btnVentanaD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVentanaD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaDActionPerformed(evt);
            }
        });
        pnlEncabezado.add(btnVentanaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 30));

        lblmin.setBackground(new java.awt.Color(255, 99, 71));
        lblmin.setFont(new java.awt.Font("FlutedGermanica", 0, 18)); // NOI18N
        lblmin.setForeground(new java.awt.Color(255, 255, 255));
        lblmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmin.setText("-");
        lblmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblminMouseMoved(evt);
            }
        });
        lblmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblminMouseExited(evt);
            }
        });
        pnlEncabezado.add(lblmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 30));

        lcliente11.setBackground(new java.awt.Color(255, 255, 255));
        lcliente11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lcliente11.setForeground(new java.awt.Color(255, 255, 255));
        lcliente11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcliente11.setText("Acerda de :");
        pnlEncabezado.add(lcliente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        jPanel4.add(pnlEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/ojo.png"))); // NOI18N
        jLabel10.setToolTipText("<html>  <style>         div{             background-color: #284564 ;             color: white;            \n font-family: fantasy;             display: flex;             align-items: center;             justify-content: center;\n                }         h3{            margin: 4px;         }     </style> <div>         <h3>            CUSCOCODE.COM        </h3>  </div> </html>");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 30, 30));

        lblvadera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/bandera.png"))); // NOI18N
        lblvadera.setToolTipText("<html>  <style>         div{             background-color: #284564 ;            \n color: white;             font-family: fantasy;             display: flex;             \nalign-items: center;             justify-content: center;                }         h3{            margin: 4px;         }     </style> <div>         <h3> PERÚ </h3>  </div> </html>");
        lblvadera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblvaderaMouseMoved(evt);
            }
        });
        lblvadera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvaderaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvaderaMouseExited(evt);
            }
        });
        jPanel4.add(lblvadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        btncerrarS.setBackground(new java.awt.Color(0, 153, 153));
        btncerrarS.setText("VISITANOS");
        btncerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarSActionPerformed(evt);
            }
        });
        jPanel4.add(btncerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
               try {
            Desktop.getDesktop().browse(URI.create("https://www.facebook.com/pages/category/Graphic-Designer/CuscoCode-101821521380078/"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void btnregistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarse1ActionPerformed
        
                 try {
            Desktop.getDesktop().browse(URI.create("https://www.pinterest.com/cuscocode/"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }//GEN-LAST:event_btnregistrarse1ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        //        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnregistrarse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarse2ActionPerformed
            // TODO add your handling code here: https://wa.me/51
        
   
            try {
            Desktop.getDesktop().browse(URI.create("https://wa.me/51984416223"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnregistrarse2ActionPerformed

    private void btnregistrarse6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarse6ActionPerformed

           try {
            Desktop.getDesktop().browse(URI.create("https://twitter.com/cuscocode"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnregistrarse6ActionPerformed

    private void btnregistrarse7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarse7ActionPerformed

        
           try {
            Desktop.getDesktop().browse(URI.create("https://www.youtube.com/watch?v=Oml1sJac3Nk&ab_channel=CuscoCode"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnregistrarse7ActionPerformed

    private void btnVentanaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaDActionPerformed

       this.dispose();
    }//GEN-LAST:event_btnVentanaDActionPerformed

    private void lblminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminMouseMoved
        // TODO add your handling code here:
        lblmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));

    }//GEN-LAST:event_lblminMouseMoved

    private void lblminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblminMouseClicked

    private void lblminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminMouseExited

        // TODO add your handling code here:
        lblmin.setBorder(null);
    }//GEN-LAST:event_lblminMouseExited
         int x,y;
    private void pnlEncabezadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEncabezadoMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlEncabezadoMouseDragged

    private void pnlEncabezadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEncabezadoMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlEncabezadoMousePressed

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        // TODO add your handling code here:
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,255)));
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

//        if (colorfond.equals("claro")) {
//            colorfond="oscuro";
//
//        }else if(colorfond.equals("oscuro")){
//            colorfond="claro";}
//
//        colorpanel(colorfond);
//
//        try {
//            FileWriter ficehero = new FileWriter(System.getProperty("user.dir")+ "/"+nombrefichero+".txt");
//            ficehero.write(colorfond);
//            ficehero.close();
//        } catch (Exception e) {
//        }

        ////////          if (colorfond.equals("b")) {
            ////////            colorfond="n";
            ////////            pnlfon.setBackground(new Color(0,0,51));
            ////////            pnlboton.setBackground(new Color(0,0,51));
            ////////            lbltexto.setForeground(new Color(0,153,255));
            //////////            panelEncabezado.setColorPrimario(new Color(0,0,51));
            //////////            panelEncabezado.setColorSecundario(new Color(0,0,51));
            ////////            lblhora.setForeground(new Color(253,19,94));
            ////////
            ////////        }else if(colorfond.equals("n")){
            ////////            colorfond="b";
            ////////            pnlfon.setBackground(Color.WHITE);
            ////////            pnlboton.setBackground(Color.WHITE);
            ////////            lbltexto.setForeground(new Color(253, 19, 94));
            //////////            panelEncabezado.setColorPrimario(Color.WHITE);
            //////////            panelEncabezado.setColorSecundario(Color.WHITE);
            ////////            lblhora.setForeground(new Color(0,153,255));
            ////////        }
        ////////
        ////////
        ////////
        ////////
        ////////
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        //        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel10.setBorder(null);

    }//GEN-LAST:event_jLabel10MouseExited

    private void lblvaderaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvaderaMouseMoved
        // TODO add your handling code here:
        lblvadera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,255)));
    }//GEN-LAST:event_lblvaderaMouseMoved

    private void lblvaderaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvaderaMouseClicked


    }//GEN-LAST:event_lblvaderaMouseClicked

    private void lblvaderaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvaderaMouseExited
        // TODO add your handling code here:
        //        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblvadera.setBorder(null);
    }//GEN-LAST:event_lblvaderaMouseExited

    private void btncerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarSActionPerformed

        
         try {
            Desktop.getDesktop().browse(URI.create("https://api.whatsapp.com/send?phone=984416223&text=Requiero%20un%20mantenimiento%20del%20software%20ticket%20"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
         
    }//GEN-LAST:event_btncerrarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_AcercaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_AcercaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_AcercaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_AcercaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_AcercaD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnVentanaD;
    private rojerusan.RSMaterialButtonRound btncerrarS;
    private rojerusan.RSMaterialButtonRound btnregistrarse;
    private rojerusan.RSMaterialButtonRound btnregistrarse1;
    private rojerusan.RSMaterialButtonRound btnregistrarse2;
    private rojerusan.RSMaterialButtonRound btnregistrarse6;
    private rojerusan.RSMaterialButtonRound btnregistrarse7;
    private rojerusan.RSButtonTriangle btnsalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblmin;
    private javax.swing.JLabel lblvadera;
    private javax.swing.JLabel lcliente11;
    private javax.swing.JLabel lcliente12;
    private javax.swing.JPanel pnlEncabezado;
    // End of variables declaration//GEN-END:variables
}
