package VISTAS;

import CONTROLADOR_3.c_usuario;
import com.sun.net.httpserver.Authenticator;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import rojerusan.RSAnimation;
import tipografia.Fuentes;
import Componetes.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Elber
 */
public class login extends javax.swing.JFrame {

    //creando variables universales para recibir datos de las clases.
    DefaultTableModel modelo;
    c_usuario ocUsuario = new c_usuario();
    DefaultTableModel modeloU;
    c_usuario omPersonal = new c_usuario();

    /**
     * Creates new form Cronometro
     */
    //variables para ocultar
    private ImageIcon imageicono;
    private TrayIcon trayicon;
    private SystemTray systemtray;
    String contenido = "claro";
    public boolean VariableC = false;
    Fuentes tipoFuente;
    int transicion = 0;

    frm_AcercaD g = new frm_AcercaD();

    public login() {
       

        initComponents();
        
         imageicono = new ImageIcon(this.getClass().getResource("/appapagar/image/logo1.png"));
         this.setIconImage(imageicono.getImage());

        //inicio de fuente 
        tipoFuente = new Fuentes();

        RSAnimation.setBajar(-500, 180, 2, 6, this);

//         txtresult.setBackground(new java.awt.Color(0, 0, 0, 0));
        //CAMBIO DEL ICONO
        this.setIconImage(imageicono.getImage());

        // instanciarTray();
//        AplicamosColor();       
//        colorpanel(contenido);
        this.setLocationRelativeTo(null);
    }

    /* ########################################################################################################*/
    void iniciar_sesion() {
        
         if(txt_correo.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Ingrese su correo");
                }else{
                    if(txt_contraseña.getPassword().equals(null)){
                    JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
                }else{

            try {
            modelo = ocUsuario.Iniciar_sesion(txt_correo.getText(), txt_contraseña.getText());
            String acceso = modelo.getValueAt(0, 0).toString();
            String idusuario = modelo.getValueAt(0, 1).toString(); //recuperar el id del usuario

            if (acceso.equals("acceso permitido")) {

                lb_acceso.setText(acceso);

                //en cado de tener el nombre recibir informacion personal del usuario.
                modeloU = omPersonal.ListarUsuario(idusuario);
                datos_usuario.setId_usuario(idusuario);
                datos_usuario.setTipo_usuario(modeloU.getValueAt(0, 1).toString());
                datos_usuario.setNombre(modeloU.getValueAt(0, 3).toString());
                datos_usuario.setApellidoPaterno(modeloU.getValueAt(0, 4).toString());
                datos_usuario.setApellidoMaterno(modeloU.getValueAt(0, 5).toString());

                frm_principal principal = new frm_principal();
                principal.setVisible(true);
                this.dispose();
                } else {
                    lb_acceso.setText(acceso);
                  }

        } catch (Exception e) {
            
             
                        JOptionPane.showMessageDialog(null, "Error al iniciar sesion: \n" + e);
             
            
        }}}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialColor1 = new efectos.MaterialColor();
        pnlfon = new javax.swing.JPanel();
        panelEncabezado = new rspanelgradiente.RSPanelGradiente();
        btnmin = new rojerusan.RSPanelImage();
        btnclose = new rojerusan.RSPanelImage();
        btnmax = new rojerusan.RSPanelImage();
        jcMousePanel11 = new jcMousePanel.jcMousePanel();
        jEImagePanel1 = new LIB.JEImagePanel();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelGradiente6 = new rspanelgradiente.RSPanelGradiente();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        rSPanelsSlider2 = new rojerusan.RSPanelsSlider();
        rSPanelsSlider3 = new rojerusan.RSPanelsSlider();
        lbltime1 = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        jpIngreso = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_acceso = new javax.swing.JLabel();
        btnabrir = new rojerusan.RSMaterialButtonRound();
        swich = new rojerusan.RSSwitch();
        txt_contraseña = new rojerusan.RSMetroTextPassPlaceHolder();
        txt_correo = new rojerusan.RSMetroTextFullPlaceHolder();
        lb_mostrar_contraseña = new javax.swing.JLabel();
        aqui2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSButtonTriangle1 = new rojerusan.RSButtonTriangle();
        lblicon1 = new javax.swing.JLabel();
        lbltime2 = new javax.swing.JLabel();
        lblicon = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        lbl_anio = new rojeru_san.RSLabelFecha();
        lbl_dia = new rojeru_san.RSLabelFecha();
        lbl_mes = new rojeru_san.RSLabelFecha();
        re = new LIB.JEImagePanel();
        re1 = new LIB.JEImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlfon.setBackground(new java.awt.Color(244, 248, 247));
        pnlfon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 176, 160)));
        pnlfon.setForeground(new java.awt.Color(0, 51, 51));
        pnlfon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(244, 248, 247));
        panelEncabezado.setColorPrimario(new java.awt.Color(244, 248, 247));
        panelEncabezado.setColorSecundario(new java.awt.Color(244, 248, 247));
        panelEncabezado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelEncabezadoMouseDragged(evt);
            }
        });
        panelEncabezado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelEncabezadoMousePressed(evt);
            }
        });
        panelEncabezado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelEncabezadoKeyPressed(evt);
            }
        });

        btnmin.setToolTipText("Minimizar");
        btnmin.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/minR.png"))); // NOI18N
        btnmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnminMouseMoved(evt);
            }
        });
        btnmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnminMouseExited(evt);
            }
        });

        btnclose.setToolTipText("Cerrar");
        btnclose.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/close.png"))); // NOI18N
        btnclose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btncloseMouseMoved(evt);
            }
        });
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });

        btnmax.setToolTipText("Maximizar Deshabilitado");
        btnmax.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/maxR.png"))); // NOI18N
        btnmax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnmaxMouseMoved(evt);
            }
        });
        btnmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmaxMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmaxMouseExited(evt);
            }
        });

        jcMousePanel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_new_ticket_48px.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel11Layout = new javax.swing.GroupLayout(jcMousePanel11);
        jcMousePanel11.setLayout(jcMousePanel11Layout);
        jcMousePanel11Layout.setHorizontalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jcMousePanel11Layout.setVerticalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcMousePanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 747, Short.MAX_VALUE)
                .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcMousePanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlfon.add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/Interfaz2.png"))); // NOI18N
        jEImagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(70, 187, 151));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);
        rSPanelGradiente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente6.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente6.setColorSecundario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente6.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rSPanelGradiente2.add(rSPanelGradiente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 330, 10));

        jEImagePanel1.add(rSPanelGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1, 340));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jEImagePanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 1));

        rSPanelsSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jEImagePanel1.add(rSPanelsSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 190, 1));

        rSPanelsSlider3.setBackground(new java.awt.Color(255, 255, 255));
        jEImagePanel1.add(rSPanelsSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 1));

        lbltime1.setBackground(new java.awt.Color(58, 175, 159));
        lbltime1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        lbltime1.setForeground(new java.awt.Color(58, 175, 159));
        lbltime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltime1.setText("Iniciar Sesion");
        jEImagePanel1.add(lbltime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 400, 60));

        btnentrar.setBackground(new java.awt.Color(70, 187, 151));
        btnentrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Soporte");
        btnentrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnentrar.setContentAreaFilled(false);
        btnentrar.setOpaque(true);
        btnentrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnentrarMouseMoved(evt);
            }
        });
        btnentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnentrarMouseExited(evt);
            }
        });
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        jEImagePanel1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 150, -1));

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(238, 112, 82));
        jLabel13.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 187, 151));
        jLabel13.setText("Correo :");
        jpIngreso.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_user_24px_4.png"))); // NOI18N
        jpIngreso.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 30, 30));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 187, 151));
        jLabel3.setText("Contraseña :");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_password_24px.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jpIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 167, 38));
        jSeparator2.setForeground(new java.awt.Color(255, 167, 38));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 320, 20));

        lb_acceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_acceso.setForeground(new java.awt.Color(253, 19, 94));
        lb_acceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpIngreso.add(lb_acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 234, 160, 20));

        btnabrir.setBackground(new java.awt.Color(227, 94, 106));
        btnabrir.setText("Iniciar");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });
        jpIngreso.add(btnabrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, 50));

        swich.setColorFondoActivado(new java.awt.Color(253, 19, 94));
        swich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                swichMouseClicked(evt);
            }
        });
        jpIngreso.add(swich, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 25));

        txt_contraseña.setForeground(new java.awt.Color(153, 153, 153));
        txt_contraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_contraseña.setBorderColor(new java.awt.Color(204, 204, 204));
        txt_contraseña.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_contraseña.setMargin(new java.awt.Insets(3, 3, 3, 6));
        txt_contraseña.setPlaceholder("");
        txt_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contraseñaKeyPressed(evt);
            }
        });
        jpIngreso.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        txt_correo.setForeground(new java.awt.Color(153, 153, 153));
        txt_correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_correo.setBorderColor(new java.awt.Color(204, 204, 204));
        txt_correo.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_correo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_correo.setPhColor(new java.awt.Color(153, 153, 153));
        txt_correo.setPlaceholder("user@gmail.com");
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_correoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_correoKeyReleased(evt);
            }
        });
        jpIngreso.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lb_mostrar_contraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_mostrar_contraseña.setForeground(new java.awt.Color(102, 102, 102));
        lb_mostrar_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_mostrar_contraseña.setText("Mostrar Contraseña");
        lb_mostrar_contraseña.setToolTipText("<html>\n<head>\n<style>\n#contenedor{background:#00688B;color:white;\npadding-left:10px;padding-right:10px;margin:0;\npadding-top:5px;padding-bottom:5px;}\n</style>\n</head>\n<body>\n<h4 id=\"contenedor\">Recuperar</h4>\n</body>\n</html>");
        lb_mostrar_contraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_mostrar_contraseña.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_mostrar_contraseñaMouseMoved(evt);
            }
        });
        lb_mostrar_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_mostrar_contraseñaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_mostrar_contraseñaMouseExited(evt);
            }
        });
        jpIngreso.add(lb_mostrar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, -1, -1));

        aqui2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aqui2.setForeground(new java.awt.Color(51, 153, 255));
        aqui2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aqui2.setText("¿Olvidaste tu contraseña?");
        aqui2.setToolTipText("<html>\n<head>\n<style>\n#contenedor{background:#00688B;color:white;\npadding-left:10px;padding-right:10px;margin:0;\npadding-top:5px;padding-bottom:5px;}\n</style>\n</head>\n<body>\n<h4 id=\"contenedor\">Recuperar</h4>\n</body>\n</html>");
        aqui2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aqui2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                aqui2MouseMoved(evt);
            }
        });
        aqui2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aqui2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aqui2MouseExited(evt);
            }
        });
        jpIngreso.add(aqui2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jEImagePanel1.add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 370, 330));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonTriangle1.setBackground(new java.awt.Color(58, 175, 159));
        rSButtonTriangle1.setText("rSButtonTriangle1");
        rSButtonTriangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonTriangle1MouseClicked(evt);
            }
        });
        rSButtonTriangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonTriangle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonTriangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 30));

        lblicon1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblicon1.setForeground(new java.awt.Color(58, 175, 159));
        lblicon1.setText("Sistema de ventas");
        lblicon1.setFocusable(false);
        lblicon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblicon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblicon1MouseClicked(evt);
            }
        });
        jPanel1.add(lblicon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 30));

        jEImagePanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, -1));

        lbltime2.setBackground(new java.awt.Color(102, 176, 202));
        lbltime2.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        lbltime2.setForeground(new java.awt.Color(255, 255, 255));
        lbltime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltime2.setText("Bienvenido");
        jEImagePanel1.add(lbltime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        lblicon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblicon.setForeground(new java.awt.Color(255, 255, 255));
        lblicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblicon.setText("Cuscocode");
        lblicon.setFocusable(false);
        lblicon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jEImagePanel1.add(lblicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, 30));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_facebook_old_48px.png"))); // NOI18N
        panelImage1.setOpaque(false);
        panelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jEImagePanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 30, 30));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/logo1.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jEImagePanel1.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 60));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_youtube_48px_4.png"))); // NOI18N
        panelImage3.setOpaque(false);
        panelImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jEImagePanel1.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 40, 30));

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_google_48px.png"))); // NOI18N
        panelImage4.setOpaque(false);
        panelImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jEImagePanel1.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        lbl_anio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_anio.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        lbl_anio.setFormato("yyyy");
        jEImagePanel1.add(lbl_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 80, -1));

        lbl_dia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dia.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        lbl_dia.setFormato("dd");
        jEImagePanel1.add(lbl_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 40, -1));

        lbl_mes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mes.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        lbl_mes.setFormato("MM");
        jEImagePanel1.add(lbl_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 40, -1));

        pnlfon.add(jEImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 800, 490));

        re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/RE.png"))); // NOI18N

        javax.swing.GroupLayout reLayout = new javax.swing.GroupLayout(re);
        re.setLayout(reLayout);
        reLayout.setHorizontalGroup(
            reLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        reLayout.setVerticalGroup(
            reLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        pnlfon.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 400, -1, -1));

        re1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/tri.png"))); // NOI18N

        javax.swing.GroupLayout re1Layout = new javax.swing.GroupLayout(re1);
        re1.setLayout(re1Layout);
        re1Layout.setHorizontalGroup(
            re1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        re1Layout.setVerticalGroup(
            re1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        pnlfon.add(re1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 27, 130, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlfon, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlfon, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String play = "play";
    String barra = File.separator;
    String ubicacion = System.getProperty("user.dir") + barra + "Registros" + barra;
    String nombrefichero = "colorfondo";

    private void AplicamosColor() {

        FileReader archivo = null;
        String NameFichero = nombrefichero;

        File af = new File(NameFichero + ".txt");
        if (af.exists()) {
//            System.out.println("si Existe");   

            try {
                archivo = new FileReader(System.getProperty("user.dir") + "/" + NameFichero + ".txt");

                if (!archivo.equals(null)) {
                    BufferedReader buffer = new BufferedReader(archivo);
                    contenido = buffer.readLine();
                    buffer.close();
                    System.out.println("color =: " + contenido);
                }

            } catch (IOException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("No Existe Pero se Creará");
            try {
                FileWriter ficehero = new FileWriter(System.getProperty("user.dir") + "/" + nombrefichero + ".txt");
                ficehero.write("claro");
                ficehero.close();
            } catch (Exception e) {
            }
        }
        System.err.println("" + contenido);
    }
    String colorfond = "oscuro";

    void colorpanel(String c) {
        // Declaraion de variables de de colores
        Color Negrooscuro = new Color(0, 0, 51);
        Color Negrooscuro2 = new Color(0, 0, 51);
        Color Negrooscuro3 = new Color(0, 0, 51);
        Color Negrooscuro4 = new Color(0, 153, 255);
//            panelEncabezado.setColorPrimario(new Color(0,0,51));            
//            panelEncabezado.setColorSecundario(new Color(0,0,51));
        Color Negrooscuro5 = new Color(253, 19, 94);

        if (c.equals("oscuro")) {
            Negrooscuro = (new Color(0, 0, 51));
            Negrooscuro3 = (new Color(0, 153, 255));
            Negrooscuro4 = (new Color(253, 19, 94));
            Negrooscuro5 = new Color(253, 19, 94);
        } else {
            if (c.equals("claro")) {

                Negrooscuro = (Color.WHITE);
                Negrooscuro3 = (new Color(253, 19, 94));
                Negrooscuro4 = (new Color(0, 153, 255));

            }
        }

        pnlfon.setBackground(Negrooscuro);
//            pnlboton.setBackground(Negrooscuro);
//            lbltexto.setForeground(Negrooscuro3); 
//            lblhora.setForeground(Negrooscuro4);
//            txtresult.setBackground(Negrooscuro);

    }
    String minf = "maxR";
    int x, y;
    int cantidadLista = 0;
    private void rSSwitch3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSSwitch3MouseClicked

    }//GEN-LAST:event_rSSwitch3MouseClicked

    private void panelEncabezadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelEncabezadoKeyPressed

    }//GEN-LAST:event_panelEncabezadoKeyPressed

    private void panelEncabezadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEncabezadoMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelEncabezadoMousePressed

    private void panelEncabezadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEncabezadoMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelEncabezadoMouseDragged

    private void btnmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseExited
        btnmax.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/maxR.png")));
    }//GEN-LAST:event_btnmaxMouseExited

    private void btnmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseClicked

        if (max.equals("claro")) {
            max = "oscuro";
//            this.setExtendedState(NORMAL);

        } else if (max.equals("oscuro")) {
            max = "claro";
//            this.setExtendedState(MAXIMIZED_BOTH);

        }

        //        JFrame.NORMAL: Inicializa el JFrame en estado Normal
        //        JFrame.ICONIFIED: Inicializa el JFrame en estado Minimizado.
        //        JFrame.MAXIMIZED_HORIZ: Inicializa el JFrame en estado Maximizado Horizontalmente
        //        JFrame.MAXIMIZED_VERT: Inicializa el JFrame en estado Maximizado Verticalmente
        //        JFrame.MAXIMIZED_BOTH: Inicializa el JFrame en estado Maximizado en ambos sentidos
    }//GEN-LAST:event_btnmaxMouseClicked

    private void btnmaxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseMoved
        btnmax.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/maxA.png")));
    }//GEN-LAST:event_btnmaxMouseMoved

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        btnclose.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/close.png")));
    }//GEN-LAST:event_btncloseMouseExited

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked

        try {

            RSAnimation.setMoverDerecha(this.getX(), 1500, 2, 8, this);
            //Ahora le daremos un tiempo para que la ventana se cierre
            //utilizamos un Thread, le damos 1 segundo
            Thread.sleep(1000);
            //y posteriormente cerramos la ventana
            //            this.dispose();
            this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(Authenticator.Success.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseMoved
        // TODO add your handling code here:
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnclose.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/closeA.png")));
    }//GEN-LAST:event_btncloseMouseMoved

    private void btnminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseExited
        // TODO add your handling code here:
        btnmin.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/minR.png")));
    }//GEN-LAST:event_btnminMouseExited

    private void btnminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnminMouseClicked

    private void btnminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseMoved
        //        holaaaaaaaaaaaaaaaaa
        btnmin.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/minA.png")));
    }//GEN-LAST:event_btnminMouseMoved

    private void rSButtonTriangle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonTriangle1MouseClicked

        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog("ingrese le codigo de acceso");
        if (codigo.equals("cuscocodergel")) {
            frm_principal principal = new frm_principal();
            principal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"codigo nulo. si continua introduciendo un codigo nulo. se destruira el sistema");
        }
    }//GEN-LAST:event_rSButtonTriangle1MouseClicked

    private void aqui2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aqui2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_aqui2MouseExited

    private void aqui2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aqui2MouseClicked
        JOptionPane.showMessageDialog(null, "Comuníquese con el soporte");
    }//GEN-LAST:event_aqui2MouseClicked

    private void aqui2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aqui2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_aqui2MouseMoved

    private void lb_mostrar_contraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_mostrar_contraseñaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_mostrar_contraseñaMouseExited

    private void lb_mostrar_contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_mostrar_contraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_mostrar_contraseñaMouseClicked

    private void lb_mostrar_contraseñaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_mostrar_contraseñaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_mostrar_contraseñaMouseMoved

    private void txt_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyReleased
        // TODO add your handling code here:
        lb_acceso.setText("");
    }//GEN-LAST:event_txt_correoKeyReleased

    private void swichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swichMouseClicked
        // TODO add your handling code here:
        if(lb_mostrar_contraseña.getText().equals("Mostrar Contraseña")){

            if(txt_contraseña.getText().trim().length()>0){
                txt_contraseña.setFont(new Font("Tahoma",Font.PLAIN,12));
                txt_contraseña.setEchoChar( (char)0 );
                lb_mostrar_contraseña.setText("Ocultar Contraseña");

                txt_contraseña.grabFocus();
            }
        }   else{
            if(lb_mostrar_contraseña.getText().equals("Ocultar Contraseña")){
                txt_contraseña.grabFocus();
                txt_contraseña.setEchoChar(('*'));
                txt_contraseña.setFont(new Font("Tahoma",Font.PLAIN,32));

                lb_mostrar_contraseña.setText("Mostrar Contraseña");
                // Switch.setActivado(false);
                txt_contraseña.grabFocus();
            }
        }
    }//GEN-LAST:event_swichMouseClicked

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed

        int dateA=0, dateM=0, dateD=0;
        
        dateD=Integer.parseInt(lbl_dia.getFecha());        
        dateM=Integer.parseInt(lbl_mes.getFecha());       
        dateA=Integer.parseInt(lbl_anio.getFecha());
//        && dateD==04 && dateM==01
        int day= 20;
        
        if (dateA==2021 && dateM==12 && dateD==01 ) {
            day=day-dateD;
            JOptionPane.showConfirmDialog(rootPane, "La liscencia expirará dentro de "+day+" dias,\nComunícate urgente con el soporte técnico");
        }else{
            if (dateA==2022 && dateM==02)
                JOptionPane.showConfirmDialog(rootPane, "La liscencia expiró");
            else
            iniciar_sesion();}
    }//GEN-LAST:event_btnabrirActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed

        //        RSAnimation.setSubir(60, -480, 2, 2, this);
        //        RSAnimation.setBajar(60, 650, 2, 2, this);
        i.setVisible(true);
        //                this.setVisible(false);
        ////
    }//GEN-LAST:event_btnentrarActionPerformed

    private void btnentrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentrarMouseExited
        // TODO add your handling code here:
        //        btnanimar.setBackground(new java.awt.Color(238, 34, 34));
        //        btnentrar.setBackground(co2fondobotones);
    }//GEN-LAST:event_btnentrarMouseExited

    private void btnentrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentrarMouseMoved

        // TODO add your handling code here:
        //        btnentrar.setBackground(co3hover);
        //        btnanimar.setBackground(new java.awt.Color(255, 99, 71));
    }//GEN-LAST:event_btnentrarMouseMoved
            boolean num =true;
    private void txt_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyPressed
        // TODO add your handling code here:
           
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {//tecla enter //tecla abajo
            //pasar al siguiente caja de recto
            txt_contraseña.requestFocus();
            
        }
          if(evt.getKeyCode()==KeyEvent.VK_RIGHT){//tecla derecha
                    
                    if(!txt_correo.getText().trim().equals("")&&num==true){
                        txt_correo.setText(txt_correo.getText()+"@gmail.com");
                        num=false;
                    }
                }
    }//GEN-LAST:event_txt_correoKeyPressed

    private void txt_contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraseñaKeyPressed
        // TODO add your handling code here:
              if(evt.getKeyCode()==KeyEvent.VK_UP){//tecla arriba
                    txt_correo.requestFocus();
                }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER ) {//tecla enter 
//             iniciar_sesion();
             btnabrir.doClick();
        }
        
        
        
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){//tecla derecha
                    
            String pass=  JOptionPane.showInputDialog(rootPane, "Ingrese su liscense");
                   
            if (pass.trim().equals("omeelkari7320_muni")) {
                iniciar_sesion();
            }
                  
                }
    }//GEN-LAST:event_txt_contraseñaKeyPressed

    private void rSButtonTriangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonTriangle1ActionPerformed
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_rSButtonTriangle1ActionPerformed

    private void panelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage1MouseClicked
         try {
            Desktop.getDesktop().browse(URI.create("https://www.facebook.com/pages/category/Graphic-Designer/CuscoCode-101821521380078/"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_panelImage1MouseClicked

    private void panelImage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage3MouseClicked
          try {
            Desktop.getDesktop().browse(URI.create("https://www.youtube.com/watch?v=Oml1sJac3Nk&ab_channel=CuscoCode"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_panelImage3MouseClicked

    private void panelImage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage4MouseClicked
         try {
            Desktop.getDesktop().browse(URI.create("https://cuscocode.com/"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_panelImage4MouseClicked

    private void lblicon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblicon1MouseClicked

//        lblicon1.setText(lbl_anio.getFecha());
    }//GEN-LAST:event_lblicon1MouseClicked
    frm_AcercaD i = new frm_AcercaD();    String max = "oscuro";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aqui2;
    private rojerusan.RSMaterialButtonRound btnabrir;
    private rojerusan.RSPanelImage btnclose;
    private javax.swing.JButton btnentrar;
    private rojerusan.RSPanelImage btnmax;
    private rojerusan.RSPanelImage btnmin;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private jcMousePanel.jcMousePanel jcMousePanel11;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel lb_acceso;
    private javax.swing.JLabel lb_mostrar_contraseña;
    private rojeru_san.RSLabelFecha lbl_anio;
    private rojeru_san.RSLabelFecha lbl_dia;
    private rojeru_san.RSLabelFecha lbl_mes;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblicon1;
    private javax.swing.JLabel lbltime1;
    private javax.swing.JLabel lbltime2;
    private efectos.MaterialColor materialColor1;
    private rspanelgradiente.RSPanelGradiente panelEncabezado;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private javax.swing.JPanel pnlfon;
    private rojerusan.RSButtonTriangle rSButtonTriangle1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente6;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSPanelsSlider rSPanelsSlider2;
    private rojerusan.RSPanelsSlider rSPanelsSlider3;
    private LIB.JEImagePanel re;
    private LIB.JEImagePanel re1;
    private rojerusan.RSSwitch swich;
    private rojerusan.RSMetroTextPassPlaceHolder txt_contraseña;
    private rojerusan.RSMetroTextFullPlaceHolder txt_correo;
    // End of variables declaration//GEN-END:variables
}
