/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

//import COMPONENTES.Mensaje_Dialogo2;
//import CONTROLADOR_3.c_usuario;
//import static VISTA.frm_principal.pnlMenu;
import CONTROLADOR_3.c_precio;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

import Componetes.ManejoDeImagenes;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author raul hacho cutipa
 */
public class pnl_precio extends javax.swing.JPanel {

    DefaultTableModel modeloP;
    c_precio omPrecio = new c_precio();

    //------------------------------------------------
    //  frm_principal frmPrincipal = new frm_principal();
//    c_usuario omPersonal = new c_usuario();
    public pnl_precio() {
        initComponents();
        txt_id.setEnabled(false);
        listar("");

    }

    void limpiar() {
        txt_id.setText("");
        txt_precio_adulto.setText("");
        txt_infantil.setText("");
        txt_nombre_precio.setText("");
    }

    void listar(String dato) {
        try {
            modeloP = omPrecio.ListarPrecio(dato);
            tabla.setModel(modeloP);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "error al listar los precios");
        }
    }

    void insertar() {
        try {
            if (txt_precio_adulto.getText().isEmpty() || txt_infantil.getText().isEmpty()) {

                JOptionPane.showConfirmDialog(null, "complete los campos");
            } else {
                omPrecio.insertarPrecio(Double.parseDouble(txt_precio_adulto.getText()), Double.parseDouble(txt_infantil.getText()), txt_nombre_precio.getText());
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error al insertar datos cliente");
        }
    }

    void recuperar_usuario() {
        int select = tabla.getSelectedRow();
        txt_id.setText(modeloP.getValueAt(select, 0).toString());
        txt_precio_adulto.setText(modeloP.getValueAt(select, 1).toString());
        txt_infantil.setText(modeloP.getValueAt(select, 2).toString());
        txt_nombre_precio.setText(modeloP.getValueAt(select, 3).toString());

    }

    void modificar() {
        try {
            if (txt_id.getText().isEmpty() || txt_precio_adulto.getText().isEmpty() || txt_infantil.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "complete los campos");
            } else {
                omPrecio.modificarPrecio(txt_id.getText(), Double.parseDouble(txt_precio_adulto.getText()), Double.parseDouble(txt_infantil.getText()),txt_nombre_precio.getText());
                limpiar();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "ocurrio un error al modificar");
        }
    }

    void eliminar() {
        try {

            int sselect = tabla.getSelectedRow();
            if (sselect >= 0) {
                omPrecio.eliminarPrecio(modeloP.getValueAt(sselect, 0).toString());
            } else {

                JOptionPane.showMessageDialog(null, "selecione para eliminar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error al eliminar los precios");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButon = new javax.swing.ButtonGroup();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jpanel_n = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lcodigo6 = new javax.swing.JLabel();
        lcodigo7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lcodigo1 = new javax.swing.JLabel();
        lcodigo3 = new javax.swing.JLabel();
        lcodigo4 = new javax.swing.JLabel();
        lcodigo5 = new javax.swing.JLabel();
        lcodigo8 = new javax.swing.JLabel();
        lcodigo9 = new javax.swing.JLabel();
        lcodigo10 = new javax.swing.JLabel();
        lcodigo2 = new javax.swing.JLabel();
        jpanel_a = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lcodigo11 = new javax.swing.JLabel();
        lcodigo12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lcodigo13 = new javax.swing.JLabel();
        lcodigo14 = new javax.swing.JLabel();
        lcodigo15 = new javax.swing.JLabel();
        lcodigo16 = new javax.swing.JLabel();
        lcodigo17 = new javax.swing.JLabel();
        lcodigo18 = new javax.swing.JLabel();
        lcodigo19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        jPanel7 = new javax.swing.JPanel();
        lcodigo20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_buscar = new LIB.JTexfieldPH_FielTex();
        jcMousePanel6 = new jcMousePanel.jcMousePanel();
        rSPanelGradiente3 = new rspanelgradiente.RSPanelGradiente();
        lblImagen = new rojerusan.RSPanelCircleImage();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new rojeru_san.RSMTextFull();
        lblpass = new javax.swing.JLabel();
        btn_Eliminar = new rojerusan.RSMaterialButtonRound();
        txt_infantil = new rojeru_san.RSMTextFull();
        txt_precio_adulto = new rojeru_san.RSMTextFull();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        lcodigo = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        jcMousePanel11 = new jcMousePanel.jcMousePanel();
        lblcorreo2 = new javax.swing.JLabel();
        lblcorreo3 = new javax.swing.JLabel();
        lblcorreo4 = new javax.swing.JLabel();
        rSPanelGradiente4 = new rspanelgradiente.RSPanelGradiente();
        rSPanelGradiente6 = new rspanelgradiente.RSPanelGradiente();
        btn_usuario3 = new rojerusan.RSMaterialButtonRound();
        btn_modificar = new rojerusan.RSMaterialButtonRound();
        txt_nombre_precio = new rojeru_san.RSMTextFull();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_n.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lcodigo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo6.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo6.setText("TOTAL ");

        lcodigo7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo7.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo7.setText(" S/ 00.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lcodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(227, 94, 106));

        lcodigo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo1.setForeground(new java.awt.Color(255, 255, 255));
        lcodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo1.setText("Precio para Niños S/ 00.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lcodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lcodigo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo3.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo3.setText("Precio 2");

        lcodigo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo4.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo4.setText("Saldo del cliente");

        lcodigo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo5.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo5.setText("Precio 1");

        lcodigo8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo8.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo8.setText(" S/ 00.00");

        lcodigo9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo9.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo9.setText(" S/ 00.00");

        lcodigo10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo10.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo10.setText(" S/ 00.00");

        javax.swing.GroupLayout jpanel_nLayout = new javax.swing.GroupLayout(jpanel_n);
        jpanel_n.setLayout(jpanel_nLayout);
        jpanel_nLayout.setHorizontalGroup(
            jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanel_nLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_nLayout.createSequentialGroup()
                        .addComponent(lcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lcodigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_nLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lcodigo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_nLayout.createSequentialGroup()
                        .addComponent(lcodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lcodigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpanel_nLayout.setVerticalGroup(
            jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_nLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelGradiente1.add(jpanel_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 290, 240));

        lcodigo2.setFont(new java.awt.Font("techno overload BRK", 0, 48)); // NOI18N
        lcodigo2.setForeground(new java.awt.Color(227, 94, 106));
        lcodigo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo2.setText("Precios a Pagar");
        rSPanelGradiente1.add(lcodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 410, 50));

        jpanel_a.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lcodigo11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo11.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo11.setText("TOTAL ");

        lcodigo12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo12.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo12.setText(" S/ 00.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lcodigo11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcodigo12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(70, 187, 151));

        lcodigo13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo13.setForeground(new java.awt.Color(255, 255, 255));
        lcodigo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo13.setText("Precio para Adultos S/ 00.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcodigo13, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lcodigo13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lcodigo14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo14.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo14.setText("Precio 2");

        lcodigo15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo15.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo15.setText("Saldo del cliente");

        lcodigo16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo16.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo16.setText("Precio 1");

        lcodigo17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo17.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo17.setText(" S/ 00.00");

        lcodigo18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo18.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo18.setText(" S/ 00.00");

        lcodigo19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo19.setForeground(new java.awt.Color(153, 153, 153));
        lcodigo19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lcodigo19.setText(" S/ 00.00");

        javax.swing.GroupLayout jpanel_aLayout = new javax.swing.GroupLayout(jpanel_a);
        jpanel_a.setLayout(jpanel_aLayout);
        jpanel_aLayout.setHorizontalGroup(
            jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanel_aLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_aLayout.createSequentialGroup()
                        .addComponent(lcodigo14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lcodigo17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_aLayout.createSequentialGroup()
                        .addComponent(lcodigo15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lcodigo19, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_aLayout.createSequentialGroup()
                        .addComponent(lcodigo16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lcodigo18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpanel_aLayout.setVerticalGroup(
            jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_aLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jpanel_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigo17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelGradiente1.add(jpanel_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 290, 240));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, ""},
                {null, null, ""},
                {null, null, null}
            },
            new String [] {
                "Precio id", "Precio Adulto", "Precio Niño"
            }
        ));
        tabla.setAltoHead(25);
        tabla.setColorBackgoundHead(new java.awt.Color(70, 187, 151));
        tabla.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tabla.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tabla.setColorFilasBackgound2(new java.awt.Color(172, 224, 208));
        tabla.setColorFilasForeground1(new java.awt.Color(131, 209, 185));
        tabla.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        tabla.setColorSelBackgound(new java.awt.Color(50, 105, 125));
        tabla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabla.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setGrosorBordeFilas(0);
        tabla.setMultipleSeleccion(false);
        tabla.setSelectionBackground(new java.awt.Color(227, 94, 106));
        tabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaMouseMoved(evt);
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        rSPanelGradiente1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 630, 140));

        jPanel7.setBackground(new java.awt.Color(70, 187, 151));

        lcodigo20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo20.setForeground(new java.awt.Color(255, 255, 255));
        lcodigo20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo20.setText("Lista de precios");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcodigo20, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lcodigo20, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 630, 40));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 4));

        txt_buscar.setBackground(new java.awt.Color(46, 78, 114));
        txt_buscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(70, 187, 151)));
        txt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_buscar.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_buscar.setPhColor(new java.awt.Color(255, 255, 255));
        txt_buscar.setPlaceholder("BUSCAR");
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        rSPanelGradiente1.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 250, 40));

        jcMousePanel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_search_26px.png"))); // NOI18N
        jcMousePanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcMousePanel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel6Layout = new javax.swing.GroupLayout(jcMousePanel6);
        jcMousePanel6.setLayout(jcMousePanel6Layout);
        jcMousePanel6Layout.setHorizontalGroup(
            jcMousePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jcMousePanel6Layout.setVerticalGroup(
            jcMousePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(jcMousePanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 30, 30));

        rSPanelShadow1.add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 580));

        rSPanelGradiente3.setColorPrimario(new java.awt.Color(70, 114, 172));
        rSPanelGradiente3.setColorSecundario(new java.awt.Color(70, 99, 151));
        rSPanelGradiente3.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setColorBorde(new java.awt.Color(70, 187, 151));
        lblImagen.setImagen(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/RE.png"))); // NOI18N
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_cheap_2_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout lblImagenLayout = new javax.swing.GroupLayout(lblImagen);
        lblImagen.setLayout(lblImagenLayout);
        lblImagenLayout.setHorizontalGroup(
            lblImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblImagenLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );
        lblImagenLayout.setVerticalGroup(
            lblImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblImagenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        rSPanelGradiente3.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 110));

        txt_id.setBackground(new java.awt.Color(180, 186, 192));
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txt_id.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_id.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_id.setColorTransparente(true);
        txt_id.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txt_id.setPlaceholder("Numero Identificador *");
        txt_id.setSoloLetras(true);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });
        rSPanelGradiente3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 37));

        lblpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass.setForeground(new java.awt.Color(255, 255, 255));
        lblpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpass.setText("Decimales permitido");
        lblpass.setToolTipText("");
        rSPanelGradiente3.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 170, -1));

        btn_Eliminar.setBackground(new java.awt.Color(70, 187, 151));
        btn_Eliminar.setBorder(null);
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        rSPanelGradiente3.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 50));

        txt_infantil.setBackground(new java.awt.Color(46, 78, 114));
        txt_infantil.setForeground(new java.awt.Color(255, 255, 255));
        txt_infantil.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txt_infantil.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_infantil.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_infantil.setColorTransparente(true);
        txt_infantil.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txt_infantil.setPlaceholder("Precio del Niño *");
        txt_infantil.setSoloLetras(false);
        txt_infantil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_infantilKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_infantilKeyTyped(evt);
            }
        });
        rSPanelGradiente3.add(txt_infantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 180, 37));

        txt_precio_adulto.setBackground(new java.awt.Color(46, 78, 114));
        txt_precio_adulto.setForeground(new java.awt.Color(255, 255, 255));
        txt_precio_adulto.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txt_precio_adulto.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_precio_adulto.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_precio_adulto.setColorTransparente(true);
        txt_precio_adulto.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txt_precio_adulto.setPlaceholder("Precio del Adulto *");
        txt_precio_adulto.setSoloLetras(false);
        txt_precio_adulto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_precio_adultoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precio_adultoKeyTyped(evt);
            }
        });
        rSPanelGradiente3.add(txt_precio_adulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 180, 37));

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(70, 187, 151));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(70, 187, 151));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lcodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo.setText("Formulario de Precio");
        rSPanelGradiente2.add(lcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 50));

        rSPanelGradiente3.add(rSPanelGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 270, 50));

        lblcorreo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo.setText("Nro");
        rSPanelGradiente3.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 30, -1));

        jcMousePanel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appapagar/image/icons8_new_ticket_48px.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel11Layout = new javax.swing.GroupLayout(jcMousePanel11);
        jcMousePanel11.setLayout(jcMousePanel11Layout);
        jcMousePanel11Layout.setHorizontalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jcMousePanel11Layout.setVerticalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        rSPanelGradiente3.add(jcMousePanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 35, 30));

        lblcorreo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcorreo2.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo2.setText("Ingrece los precios  ®");
        rSPanelGradiente3.add(lblcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, -1));

        lblcorreo3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblcorreo3.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo3.setText("S/.");
        rSPanelGradiente3.add(lblcorreo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 30, -1));

        lblcorreo4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblcorreo4.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo4.setText("S/.");
        rSPanelGradiente3.add(lblcorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 30, -1));

        rSPanelGradiente4.setColorPrimario(new java.awt.Color(70, 187, 151));
        rSPanelGradiente4.setColorSecundario(new java.awt.Color(70, 99, 151));
        rSPanelGradiente4.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);
        rSPanelGradiente4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente6.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente6.setColorSecundario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente6.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rSPanelGradiente4.add(rSPanelGradiente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 330, 10));

        rSPanelGradiente3.add(rSPanelGradiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 1, 340));

        btn_usuario3.setBackground(new java.awt.Color(70, 187, 151));
        btn_usuario3.setBorder(null);
        btn_usuario3.setText("Guardar");
        btn_usuario3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_usuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario3ActionPerformed(evt);
            }
        });
        rSPanelGradiente3.add(btn_usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 230, 50));

        btn_modificar.setBackground(new java.awt.Color(70, 187, 151));
        btn_modificar.setBorder(null);
        btn_modificar.setText("modificar");
        btn_modificar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        rSPanelGradiente3.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 50));

        txt_nombre_precio.setBackground(new java.awt.Color(46, 78, 114));
        txt_nombre_precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre_precio.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txt_nombre_precio.setBotonColor(new java.awt.Color(70, 187, 151));
        txt_nombre_precio.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nombre_precio.setColorTransparente(true);
        txt_nombre_precio.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txt_nombre_precio.setPlaceholder("Nombre Precio *");
        txt_nombre_precio.setSoloLetras(false);
        txt_nombre_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombre_precioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_precioKeyTyped(evt);
            }
        });
        rSPanelGradiente3.add(txt_nombre_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 180, 37));

        rSPanelShadow1.add(rSPanelGradiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 370, 580));

        add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1175, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {//tecla enter //tecla abajo
            //pasar al siguiente caja de recto
            txt_precio_adulto.requestFocus();

        }

    }//GEN-LAST:event_txt_idKeyPressed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
//        librerias_raul_gabriel.validaciones.solo_texto_con_limite(evt, txt_nombre.getText(), 20);
    }//GEN-LAST:event_txt_idKeyTyped

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        eliminar();
        listar("");
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        //
        recuperar_usuario();
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed


    }//GEN-LAST:event_tablaMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseDragged

    private void tablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseMoved
        // TODO add your handling code here:
        //   Animacion.Animacion.mover_izquierda(0, -180, 2, 10, pnlMenu);
    }//GEN-LAST:event_tablaMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void txt_infantilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_infantilKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_UP) {//arriba
            //pasar al siguiente caja de recto
            txt_id.requestFocus();

        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {//tecla izquierda
            String pw = txt_infantil.getText();
            if (pw.trim().equals("")) {

                txt_precio_adulto.requestFocus();
            }

        }

    }//GEN-LAST:event_txt_infantilKeyPressed

    private void txt_infantilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_infantilKeyTyped
        librerias_raul_gabriel.validaciones.solo_numeros_decimales_con_limite(evt, txt_infantil.getText(), 5);
    }//GEN-LAST:event_txt_infantilKeyTyped

    private void txt_precio_adultoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precio_adultoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {//tecla enter //tecla abajo
            //pasar al siguiente caja de recto
            txt_infantil.requestFocus();

        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {//arriba
            //pasar al siguiente caja de recto
            txt_id.requestFocus();

        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {//arriba
            //pasar al siguiente caja de recto
            txt_infantil.requestFocus();

        }
    }//GEN-LAST:event_txt_precio_adultoKeyPressed

    private void txt_precio_adultoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precio_adultoKeyTyped
        librerias_raul_gabriel.validaciones.solo_numeros_decimales_con_limite(evt, txt_precio_adulto.getText(), 5);
    }//GEN-LAST:event_txt_precio_adultoKeyTyped


    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
//        if (evt.getClickCount() == 2) {
//            System.out.println("double clicked");
//            try {
//                String url = ""+archivo;
//                ProcessBuilder p= new ProcessBuilder();
//                p.command("cmd.exe","/c",url);
//                p.start();
//            } catch (IOException ex) {
//                Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
//            }
//
//        }
    }//GEN-LAST:event_lblImagenMouseClicked

    private void btn_usuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario3ActionPerformed
        // TODO add your handling code here:
        insertar();
        listar("");
    }//GEN-LAST:event_btn_usuario3ActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        modificar();
        listar("");
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:
        listar(txt_buscar.getText());
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void jcMousePanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcMousePanel6MouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("https://www.facebook.com/pages/category/Graphic-Designer/CuscoCode-101821521380078/"));
        } catch (IOException e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jcMousePanel6MouseClicked

    private void txt_nombre_precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_precioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_precioKeyPressed

    private void txt_nombre_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_precioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_precioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRound btn_Eliminar;
    private rojerusan.RSMaterialButtonRound btn_modificar;
    private rojerusan.RSMaterialButtonRound btn_usuario3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel11;
    private jcMousePanel.jcMousePanel jcMousePanel6;
    private javax.swing.JPanel jpanel_a;
    private javax.swing.JPanel jpanel_n;
    private rojerusan.RSPanelCircleImage lblImagen;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblcorreo2;
    private javax.swing.JLabel lblcorreo3;
    private javax.swing.JLabel lblcorreo4;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcodigo1;
    private javax.swing.JLabel lcodigo10;
    private javax.swing.JLabel lcodigo11;
    private javax.swing.JLabel lcodigo12;
    private javax.swing.JLabel lcodigo13;
    private javax.swing.JLabel lcodigo14;
    private javax.swing.JLabel lcodigo15;
    private javax.swing.JLabel lcodigo16;
    private javax.swing.JLabel lcodigo17;
    private javax.swing.JLabel lcodigo18;
    private javax.swing.JLabel lcodigo19;
    private javax.swing.JLabel lcodigo2;
    private javax.swing.JLabel lcodigo20;
    private javax.swing.JLabel lcodigo3;
    private javax.swing.JLabel lcodigo4;
    private javax.swing.JLabel lcodigo5;
    private javax.swing.JLabel lcodigo6;
    private javax.swing.JLabel lcodigo7;
    private javax.swing.JLabel lcodigo8;
    private javax.swing.JLabel lcodigo9;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente3;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente4;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente6;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.ButtonGroup radioButon;
    private rojerusan.RSTableMetro tabla;
    private LIB.JTexfieldPH_FielTex txt_buscar;
    private rojeru_san.RSMTextFull txt_id;
    private rojeru_san.RSMTextFull txt_infantil;
    private rojeru_san.RSMTextFull txt_nombre_precio;
    private rojeru_san.RSMTextFull txt_precio_adulto;
    // End of variables declaration//GEN-END:variables
}
