/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

//import COMPONENTES.Mensaje_Dialogo2;
//import CONTROLADOR_3.c_usuario;
//import static VISTA.frm_principal.pnlMenu;
import CONTROLADOR_3.c_cliente;
import CONTROLADOR_3.c_ventas;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

import Componetes.ManejoDeImagenes;
import Componetes.datos_usuario;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import rojerusan.RSDateChooser;

/**
 *
 * @author raul hacho cutipa
 */
public class pnl_reportes_p extends javax.swing.JPanel {

    DefaultTableModel modeloV, modeloU;
    private ImageIcon imageicono;
    c_ventas omVentas = new c_ventas();
    //------------------------------------------------

    //  frm_principal frmPrincipal = new frm_principal();
//    c_usuario omPersonal = new c_usuario();
    public pnl_reportes_p() {
        initComponents();
        listar_reporte();

        imageicono = new ImageIcon(this.getClass().getResource("/appapagar/image/logo1.png"));
//        private ImageIcon imageicono;

    }

    public void listar_reporte() {
        try {
            modeloV = omVentas.ListarReporte_personal(datos_usuario.getId_usuario());
            // tabla_usuarios.setModel(modeloU);
            lb_id.setText(modeloV.getValueAt(0, 0).toString());
            lb_nombre.setText(modeloV.getValueAt(0, 1).toString());
            lb_dni.setText(modeloV.getValueAt(0, 2).toString());
            lb_correo.setText(modeloV.getValueAt(0, 3).toString());
            lb_telefono.setText(modeloV.getValueAt(0, 4).toString());

            lb_ganancias.setText(modeloV.getValueAt(0, 5).toString());
            lb_ventas.setText(modeloV.getValueAt(0, 6).toString());
            lb_adultos.setText(modeloV.getValueAt(0, 7).toString());
            lb_niños.setText(modeloV.getValueAt(0, 8).toString());
            lb_personas.setText(modeloV.getValueAt(0, 9).toString());

            lb_locales.setText(modeloV.getValueAt(0, 10).toString());
            lb_externos.setText(modeloV.getValueAt(0, 11).toString());
            lb_extranjerso.setText(modeloV.getValueAt(0, 12).toString());
            reportes_hoy();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error al listar reporte_usuario \n" + e);
        }
    }

    private void reportes_hoy() {
        try {
            LocalDate fecha = LocalDate.now();
            //String fechaHoy = fecha.getYear() + "-" + fecha.getMonthValue() + "-" + fecha.getDayOfYear();

            modeloU = omVentas.ListarReporte_personal_ventas_hoy(datos_usuario.getId_usuario(), fecha.toString());
            if (modeloU.getRowCount() > 0) {
                lb_adultos_hoy.setText(modeloU.getValueAt(0, 0).toString());
                lb_niños_hoy.setText(modeloU.getValueAt(0, 1).toString());
                lb_venta_hoy.setText(modeloU.getValueAt(0, 2).toString());
                lb_ganancias_hoy.setText(modeloU.getValueAt(0, 3).toString());
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "ubo un probelma al mostrar repotes de hoy");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButon = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lcodigo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jpanel_n = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_avizos = new javax.swing.JLabel();
        lcodigo4 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lcodigo5 = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_dni = new javax.swing.JLabel();
        lcodigo7 = new javax.swing.JLabel();
        lcodigo8 = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lcodigo9 = new javax.swing.JLabel();
        jpanel_n1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lb_avizos1 = new javax.swing.JLabel();
        lcodigo11 = new javax.swing.JLabel();
        lb_ganancias = new javax.swing.JLabel();
        lcodigo14 = new javax.swing.JLabel();
        lb_ventas = new javax.swing.JLabel();
        lcodigo15 = new javax.swing.JLabel();
        lb_adultos = new javax.swing.JLabel();
        lcodigo16 = new javax.swing.JLabel();
        lb_niños = new javax.swing.JLabel();
        lb_extranjerso = new javax.swing.JLabel();
        lcodigo17 = new javax.swing.JLabel();
        lcodigo18 = new javax.swing.JLabel();
        lb_externos = new javax.swing.JLabel();
        lb_locales = new javax.swing.JLabel();
        lb_personas = new javax.swing.JLabel();
        lcodigo19 = new javax.swing.JLabel();
        lcodigo20 = new javax.swing.JLabel();
        btn_modeficar1 = new rojerusan.RSMaterialButtonRound();
        jpanel_n2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lcodigo6 = new javax.swing.JLabel();
        lb_ganancias_hoy = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb_avizos2 = new javax.swing.JLabel();
        lbl_fecha1 = new rojeru_san.RSLabelFecha();
        lcodigo10 = new javax.swing.JLabel();
        lcodigo12 = new javax.swing.JLabel();
        lb_niños_hoy = new javax.swing.JLabel();
        lb_adultos_hoy = new javax.swing.JLabel();
        lcodigo13 = new javax.swing.JLabel();
        lb_venta_hoy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lcodigo2.setFont(new java.awt.Font("techno overload BRK", 0, 48)); // NOI18N
        lcodigo2.setForeground(new java.awt.Color(227, 94, 106));
        lcodigo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo2.setText(" Reporte del usuario");
        add(lcodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 820, 50));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, 4));

        jpanel_n.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel1.setBackground(new java.awt.Color(227, 94, 106));

        lb_avizos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_avizos.setForeground(new java.awt.Color(255, 255, 255));
        lb_avizos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_avizos.setText("DATOS DEL USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_avizos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_avizos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lcodigo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo4.setForeground(new java.awt.Color(102, 102, 102));
        lcodigo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo4.setText("ID USUARIO:");

        lb_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_id.setForeground(new java.awt.Color(153, 153, 153));
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_id.setText("0");

        lcodigo5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo5.setForeground(new java.awt.Color(102, 102, 102));
        lcodigo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo5.setText("NOMBRES:");

        lb_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_nombre.setForeground(new java.awt.Color(153, 153, 153));
        lb_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_nombre.setText("0");

        lb_dni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_dni.setForeground(new java.awt.Color(153, 153, 153));
        lb_dni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_dni.setText("0");

        lcodigo7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo7.setForeground(new java.awt.Color(102, 102, 102));
        lcodigo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo7.setText("DNI:");

        lcodigo8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo8.setForeground(new java.awt.Color(102, 102, 102));
        lcodigo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo8.setText("CORREO:");

        lb_correo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_correo.setForeground(new java.awt.Color(153, 153, 153));
        lb_correo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_correo.setText("0");

        lb_telefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_telefono.setForeground(new java.awt.Color(153, 153, 153));
        lb_telefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_telefono.setText("0");

        lcodigo9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcodigo9.setForeground(new java.awt.Color(102, 102, 102));
        lcodigo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo9.setText("TELEFONO:");

        javax.swing.GroupLayout jpanel_nLayout = new javax.swing.GroupLayout(jpanel_n);
        jpanel_n.setLayout(jpanel_nLayout);
        jpanel_nLayout.setHorizontalGroup(
            jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanel_nLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lcodigo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcodigo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcodigo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcodigo4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lcodigo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_dni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanel_nLayout.setVerticalGroup(
            jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_nLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_nLayout.createSequentialGroup()
                        .addComponent(lcodigo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodigo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodigo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodigo8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcodigo9))
                    .addGroup(jpanel_nLayout.createSequentialGroup()
                        .addComponent(lb_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_dni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_correo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_telefono)))
                .addGap(292, 292, 292))
        );

        add(jpanel_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 460, 220));

        jpanel_n1.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel4.setBackground(new java.awt.Color(240, 184, 1));

        lb_avizos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_avizos1.setForeground(new java.awt.Color(255, 255, 255));
        lb_avizos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_avizos1.setText("REPORTE DE LAS VENTAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lb_avizos1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_avizos1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lcodigo11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo11.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo11.setText("GANANCIAS REALIZADAS");

        lb_ganancias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ganancias.setForeground(new java.awt.Color(51, 51, 51));
        lb_ganancias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_ganancias.setText("0");

        lcodigo14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo14.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo14.setText("VENTAS REALIZADAS");

        lb_ventas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ventas.setForeground(new java.awt.Color(51, 51, 51));
        lb_ventas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_ventas.setText("0");

        lcodigo15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo15.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo15.setText("ADULTOS ATENDIDOS:");

        lb_adultos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_adultos.setForeground(new java.awt.Color(51, 51, 51));
        lb_adultos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_adultos.setText("0");

        lcodigo16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo16.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo16.setText("NIÑOS ATENDIDOS:");

        lb_niños.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_niños.setForeground(new java.awt.Color(51, 51, 51));
        lb_niños.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_niños.setText("0");

        lb_extranjerso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_extranjerso.setForeground(new java.awt.Color(51, 51, 51));
        lb_extranjerso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_extranjerso.setText("0");

        lcodigo17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo17.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo17.setText("CLIENTES EXTRANJEROS:");

        lcodigo18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo18.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo18.setText("CLIENTES EXTERNO:");

        lb_externos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_externos.setForeground(new java.awt.Color(51, 51, 51));
        lb_externos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_externos.setText("0");

        lb_locales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_locales.setForeground(new java.awt.Color(51, 51, 51));
        lb_locales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_locales.setText("0");

        lb_personas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_personas.setForeground(new java.awt.Color(51, 51, 51));
        lb_personas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_personas.setText("0");

        lcodigo19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo19.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo19.setText("TOTAL PERSONAS:");

        lcodigo20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo20.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo20.setText("CLIENTES LOCALES:");

        javax.swing.GroupLayout jpanel_n1Layout = new javax.swing.GroupLayout(jpanel_n1);
        jpanel_n1.setLayout(jpanel_n1Layout);
        jpanel_n1Layout.setHorizontalGroup(
            jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_n1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_n1Layout.createSequentialGroup()
                        .addComponent(lcodigo17, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_extranjerso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_n1Layout.createSequentialGroup()
                        .addComponent(lcodigo18, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_externos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpanel_n1Layout.createSequentialGroup()
                            .addComponent(lcodigo20, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_locales, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanel_n1Layout.createSequentialGroup()
                            .addComponent(lcodigo19, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_n1Layout.createSequentialGroup()
                        .addComponent(lcodigo16, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_niños, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_n1Layout.createSequentialGroup()
                        .addComponent(lcodigo15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_adultos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpanel_n1Layout.createSequentialGroup()
                            .addComponent(lcodigo14, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanel_n1Layout.createSequentialGroup()
                            .addComponent(lcodigo11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_ganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jpanel_n1Layout.setVerticalGroup(
            jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_n1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ganancias)
                    .addComponent(lcodigo11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ventas)
                    .addComponent(lcodigo14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_adultos)
                    .addComponent(lcodigo15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_niños)
                    .addComponent(lcodigo16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_personas)
                    .addComponent(lcodigo19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_locales)
                    .addComponent(lcodigo20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_externos)
                    .addComponent(lcodigo18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_extranjerso)
                    .addComponent(lcodigo17))
                .addGap(208, 208, 208))
        );

        add(jpanel_n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 580, 300));

        btn_modeficar1.setBackground(new java.awt.Color(70, 187, 151));
        btn_modeficar1.setBorder(null);
        btn_modeficar1.setText("IMPRIMIR");
        btn_modeficar1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_modeficar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modeficar1ActionPerformed(evt);
            }
        });
        add(btn_modeficar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 450, 50));

        jpanel_n2.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lcodigo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo6.setForeground(new java.awt.Color(51, 51, 51));
        lcodigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcodigo6.setText("GANANCIA TOTAL");

        lb_ganancias_hoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ganancias_hoy.setForeground(new java.awt.Color(51, 51, 51));
        lb_ganancias_hoy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_ganancias_hoy.setText(" S/ 00.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lcodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(lb_ganancias_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ganancias_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBackground(new java.awt.Color(70, 187, 151));

        lb_avizos2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_avizos2.setForeground(new java.awt.Color(255, 255, 255));
        lb_avizos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_avizos2.setText("GANANCIAS   DE HOY :");

        lbl_fecha1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_avizos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_avizos2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lcodigo10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo10.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo10.setText("Adultos Atendidos:");

        lcodigo12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo12.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo12.setText("Niños Atendidos:");

        lb_niños_hoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_niños_hoy.setForeground(new java.awt.Color(153, 153, 153));
        lb_niños_hoy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_niños_hoy.setText("0");

        lb_adultos_hoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_adultos_hoy.setForeground(new java.awt.Color(153, 153, 153));
        lb_adultos_hoy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_adultos_hoy.setText("0");

        lcodigo13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo13.setForeground(new java.awt.Color(204, 204, 204));
        lcodigo13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lcodigo13.setText("Ventas Realizadas:");

        lb_venta_hoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_venta_hoy.setForeground(new java.awt.Color(153, 153, 153));
        lb_venta_hoy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_venta_hoy.setText("0");

        javax.swing.GroupLayout jpanel_n2Layout = new javax.swing.GroupLayout(jpanel_n2);
        jpanel_n2.setLayout(jpanel_n2Layout);
        jpanel_n2Layout.setHorizontalGroup(
            jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanel_n2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_n2Layout.createSequentialGroup()
                        .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lcodigo10, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(lcodigo12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_niños_hoy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_adultos_hoy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_n2Layout.createSequentialGroup()
                        .addComponent(lcodigo13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(lb_venta_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jpanel_n2Layout.setVerticalGroup(
            jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_n2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_adultos_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_niños_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_venta_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpanel_n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 460, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseDragged

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved
    JFileChooser file = new JFileChooser();

    private Font FuenteBold = new Font(Font.FontFamily.UNDEFINED, 7, Font.UNDERLINE);
    private Font Fuentenegrita = new Font(Font.FontFamily.UNDEFINED, 8, Font.BOLD);
    private Font FuenteNormal = new Font(Font.FontFamily.UNDEFINED, 7, Font.NORMAL);
    private Font FuenteItalic = new Font(Font.FontFamily.COURIER, 7, Font.ITALIC);

    private Paragraph getnegrita(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(Fuentenegrita);
        p.add(c);
        return p;
    }

    private Paragraph getInfo(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(Fuentenegrita);
        p.add(c);
        return p;
    }

    private Paragraph getfecha(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(Fuentenegrita);
        p.add(c);
        return p;
    }

    private Paragraph getFooter(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(Fuentenegrita);
        p.add(c);
        return p;
    }
    private void btn_modeficar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modeficar1ActionPerformed

//          String nombrepdf = "C:/Users/USER/Documents/aa.pdf";
        String nombrepdf = System.getProperty("user.dir")+"/Reporte_personal.pdf";

//        String nombrepdf = "C:/Users/mr-robot/Documents/DOCUMENTO/blog.pdf";
        try {
            //tamanio de la hoja -margenes - top -- footer
            Document document = new Document(PageSize.A7, 20, 20, -10, 0);
            PdfWriter.getInstance(document, new FileOutputStream(nombrepdf));
            document.open();

            document.add(getnegrita("Humedal - Huasao"));
            document.add(getInfo("Reporte de ventas"));
            document.add(getfecha(lbl_fecha1.getFecha()));

//-----------------------------*
            Font negrita = new Font(Font.FontFamily.UNDEFINED, 7, Font.BOLD, BaseColor.BLACK);

            Font blue = new Font(Font.FontFamily.UNDEFINED, 7, Font.NORMAL, BaseColor.BLACK);

//          document.add(new Paragraph(Chunk.NEWLINE));
            Font normal = new Font(Font.FontFamily.UNDEFINED, 7, Font.NORMAL, BaseColor.BLACK);
            Chunk greenText = new Chunk("CODIGO : ", negrita);
            Chunk dni = new Chunk(lb_id.getText() + "\n", negrita);
            //fecha entre dos

            Chunk d12 = new Chunk("NOMBRE : ", negrita);
            Chunk dprope = new Chunk(lb_nombre.getText() + "\n", normal);

            Chunk d14 = new Chunk("DNI : ", negrita);
            Chunk p11 = new Chunk(lb_dni.getText() + "\n", normal);

            Chunk p12 = new Chunk("CANT. ADULTOS : ", negrita);
            Chunk p13 = new Chunk(lb_adultos_hoy.getText() + "\n", normal);

            Chunk p14 = new Chunk("CANT. NIÑOS : ", negrita);
            Chunk p15 = new Chunk(lb_niños_hoy.getText() + "\n", normal);

            Chunk p16 = new Chunk("CANT. DE VENTAS : ", negrita);
            Chunk p17 = new Chunk(lb_venta_hoy.getText() + "\n", normal);

            Chunk p18 = new Chunk("GANANCIA TOTAL : ", negrita);
            Chunk p19 = new Chunk(lb_ganancias_hoy.getText() + "\n", normal);

            Paragraph p2 = new Paragraph();
            p2.setAlignment(Element.ALIGN_JUSTIFIED);

            p2.add(greenText);
            p2.add(dni);
            p2.add(d12);
            p2.add(dprope);
            p2.add(d14);
            p2.add(p11);
            p2.add(p12);
            p2.add(p13);
            p2.add(p14);
            p2.add(p15);
            p2.add(p16);
            p2.add(p17);
            p2.add(p18);
            p2.add(p19);

            document.add(p2);

            document.add(getFooter("cuscocode.com"));

            document.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(lb_nombre, e);
        }

        try {
            String url = nombrepdf;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe", "/c", url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_modeficar1ActionPerformed
//frm_principal panel= new frm_principal();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRound btn_modeficar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jpanel_n;
    private javax.swing.JPanel jpanel_n1;
    private javax.swing.JPanel jpanel_n2;
    private javax.swing.JLabel lb_adultos;
    private javax.swing.JLabel lb_adultos_hoy;
    private javax.swing.JLabel lb_avizos;
    private javax.swing.JLabel lb_avizos1;
    private javax.swing.JLabel lb_avizos2;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_dni;
    private javax.swing.JLabel lb_externos;
    private javax.swing.JLabel lb_extranjerso;
    private javax.swing.JLabel lb_ganancias;
    private javax.swing.JLabel lb_ganancias_hoy;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_locales;
    private javax.swing.JLabel lb_niños;
    private javax.swing.JLabel lb_niños_hoy;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_personas;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JLabel lb_venta_hoy;
    private javax.swing.JLabel lb_ventas;
    private rojeru_san.RSLabelFecha lbl_fecha1;
    private javax.swing.JLabel lcodigo10;
    private javax.swing.JLabel lcodigo11;
    private javax.swing.JLabel lcodigo12;
    private javax.swing.JLabel lcodigo13;
    private javax.swing.JLabel lcodigo14;
    private javax.swing.JLabel lcodigo15;
    private javax.swing.JLabel lcodigo16;
    private javax.swing.JLabel lcodigo17;
    private javax.swing.JLabel lcodigo18;
    private javax.swing.JLabel lcodigo19;
    private javax.swing.JLabel lcodigo2;
    private javax.swing.JLabel lcodigo20;
    private javax.swing.JLabel lcodigo4;
    private javax.swing.JLabel lcodigo5;
    private javax.swing.JLabel lcodigo6;
    private javax.swing.JLabel lcodigo7;
    private javax.swing.JLabel lcodigo8;
    private javax.swing.JLabel lcodigo9;
    private javax.swing.ButtonGroup radioButon;
    // End of variables declaration//GEN-END:variables
}
